apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: kube-auth-test
spec:
  selector:
    matchLabels:
      app: kube-auth-test
  template:
    metadata:
      labels:
        app: kube-auth-test
    spec:
      containers:
      - image: kapopken/kube-auth-test
        name: kube-auth-test
        ports:
        - containerPort: 80
          name: kube-auth-test
        volumeMounts:
        - name: credential
          mountPath: /var/dist
      volumes:
        - name: credential
          secret:
            secretName: credential