apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  env: dev
bases:
- ../../base
patchesStrategicMerge:
- custom-env.yaml
- configmap.yaml
images:
- name: kapopken/kube-auth-test
  newTag: "3.6"
