apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-auth-express.fullname" . }}
configuration:
- credential: {{ .Values.configMap.credientials.foo }}
  path: /foo
- credential: {{ .Values.configMap.credientials.bar }}
  path: /bar