apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-auth-express.fullname" . }}
data:
 configuration: | 
  configuration:
  - credential: {{ .Values.configMap.credential.foo }}
    path: /foo
  - credential: {{ .Values.configMap.credential.bar }}
    path: /bar