{{- if .Values.ingress.enabled -}}
{{- $fullName := include "kube-auth-express.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ include "kube-auth-express.name" . }}
    helm.sh/chart: {{ include "kube-auth-express.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
   - http:
      paths:
       - path: {{ .Values.ingress.path }}
         backend:
          serviceName: {{ $fullName }}
          servicePort: 80
{{- end }}
